### ISSUE TITLE
Keyda 3.6 运行时出错

### ISSUE THREAD

**Issue by Karonzhjr** [miaomiaosoft/Keyda#11]
![Snipaste_2019-06-26_11-31-58](https://user-images.githubusercontent.com/44044519/60149104-23d68d80-9806-11e9-8edb-d80056eee68e.png)
win 10 1903 64bit
keyda 3.6

**Comment by miaomiaosoft** [comment]
删除CONFIG.INI文件重启
或
不勾选内存播放
或
用回3.5是否正常

**Comment by Karonzhjr** [comment]
> 删除CONFIG.INI文件重启
> 或
> 不勾选内存播放
> 或
> 用回3.5是否正常

用3.5正常，好的，3.6我不勾选内存播放试用看看

**Comment by miaomiaosoft** [comment]
问一下，上面那个错误是在什么操作之后触发的
能确定是勾选内存播放才出现的吧
那是软件启动后立马出错还是换音效后出错或是其他操作？

我个人遇到当频繁更换音效后有机会出错

**Comment by Karonzhjr** [comment]
我勾选了内存播放并换了音效，但不频繁，然后就用了一会儿就报错了。
3.6我昨天取消了内存播放，到现在还没出错。

**Comment by Karonzhjr** [comment]
![Snipaste_2019-06-28_06-47-31](https://user-images.githubusercontent.com/44044519/60305862-a5e2c580-9970-11e9-986e-5b4e6adc19ca.png)
开机运行了几分钟，期间就浏览器了几个网页就又出错了。

**Comment by miaomiaosoft** [comment]
你有装虚拟机吗，不嫌麻烦的话有的话放虚拟机运行看看，我这WIN7一直内存播放没有这问题，上面说的频繁更换音效导致的出错也不是你这种的提示

**Comment by Karonzhjr** [comment]
不好意思呀，我有安装VMware虚拟机，但是Ubuntu系统。
再次启动QQ，keyda3.6又再次出错哦
ok，我还是用回keyda3.5哈
