### ISSUE TITLE
只要一有弹窗就会报错

### ISSUE THREAD

**Issue by Echo9742** [miaomiaosoft/Keyda#12]
运行时出错！
错误代码：4
错误信息：数组成员引用下标必须大于1

**Comment by miaomiaosoft** [comment]
可以描述具体点么

什么东西弹窗？
系统版本
软件版本
配置帖一下

**Comment by Echo9742** [comment]
像电池充电这样的弹窗，在弹出的一瞬间，就挂了
第三张图是今天早上抓的，有两个同时的弹窗，我关了一个，所以两个错误
系统是win10家庭1903（1809时也这样）



------------------ 原始邮件 ------------------
发件人: "miao_miao"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 晚上8:26
收件人: "miaomiaosoft/Keyda"<Keyda@noreply.github.com>;
抄送: "高斌"<2258289742@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [miaomiaosoft/Keyda] 只要一有弹窗就会报错 (#12)




可以描述具体点么
 
什么东西弹窗？
 系统版本
 软件版本
 配置帖一下

**Comment by miaomiaosoft** [comment]
有图？在哪呢，我没看到！

配置帖一下
有没试过不勾选内存播放是否报错
有没试过3.5或其他旧版本有没此问题

这几条有助我找到问题所在
