### ISSUE TITLE
网易有道词典在取词软件响应

### ISSUE THREAD

**Issue by fangjinggang** [miaomiaosoft/Keyda#13]
使用网易有道词典取词时  光标移置单词右上角的查词按钮时  keyda发出连续两次响应

**Comment by miaomiaosoft** [comment]
什么版本，最新的3.7有尝试解决这个问题

**Comment by Karonzhjr** [comment]
> 什么版本，最新的3.7有尝试解决这个问题

3.7版本啥时候发布呢？期待哦

**Comment by miaomiaosoft** [comment]
不好意思说错了，其实是已经发了的3.6有尝试解决这个问题
