### ISSUE TITLE
英文系统界面乱码

### ISSUE THREAD

**Issue by zzxxhhzxh** [miaomiaosoft/Keyda#14]
在使用英文的windows10 insider preview，设置中出现了乱码
![Untitled](https://user-images.githubusercontent.com/42593813/60934474-f4a33000-a28b-11e9-8d78-479cbbd434f0.jpg)

**Comment by miaomiaosoft** [comment]
不支持英文系统的，繁体系统上也会乱码，很久前有人反馈过，这是编程工具在编码上的坑，要解决的话只能把中文全翻译成英文，但软件本身主要也是给中国人用的，暂时不考虑其他语言环境，反正功能也不多，设置好了基本上很少再开这个界面了

**Comment by zzxxhhzxh** [comment]
谢谢，原来还有这么个坑。


Sincerely,
ZHOU, Xiaohuan
Ph.D, E.I.T.
Tongji University,
zzxxhhzxh@gmail.com
Texas A&M University - Kingsville,
Xiaohuan.Zhou@students.tamuk.edu
