### ISSUE TITLE
【建议意见】能不能自动切换声音播放通道

### ISSUE THREAD

**Issue by BluePointLilac** [miaomiaosoft/Keyda#16]
作者大大你好，我是Keyda的使用者，很开心能够发现你写的这款软件，给了我一些乐趣，当然也让我社会性死亡了一次。这次是提一下意见。每次打开Keyda之前如果没有插上耳机，声音通道就是喇叭，插上耳机依旧是外放；反过来如果事先插上了耳机再打开软件，就只能用耳机听到音效，如果呢拔掉耳机就没有了音效，我想问一下能不能加一个声音通道选项，自动检测切换声音通道了

**Comment by miaomiaosoft** [comment]
右键点击程序界面左上角图标会弹出菜单，最下有通道选择功能，但这功能我没严格测试，不确定好不好用，自动检测我弄不来，因为我电脑没有多个USB意源无法复现这问题

**Comment by Karonzhjr** [comment]
![Snipaste_2019-10-06_22-25-32](https://user-images.githubusercontent.com/44044519/66270621-47d74f80-e888-11e9-83c7-4ddd00a0cf9c.png)

**Comment by Karonzhjr** [comment]
Keyda 3.8 版本
