### ISSUE TITLE
Keyda 3.8 运行错误

### ISSUE THREAD

**Issue by Karonzhjr** [miaomiaosoft/Keyda#17]
![Snipaste_2019-10-06_22-25-32](https://user-images.githubusercontent.com/44044519/66270660-a3a1d880-e888-11e9-9b6e-be8c521400b1.png)
Keyda 3.8

**Comment by miaomiaosoft** [comment]
这些按键都不是标准的按键码，应该是厂商自己添加定义的，故而识别不了
我临时写了个测试程序，运行后依次按一次那排不发声的按键，然后把测试程序里的文本复制给我
[TEST.zip](https://github.com/miaomiaosoft/Keyda/files/3694664/TEST.zip)

**Comment by Karonzhjr** [comment]
![Snipaste_2019-10-07_12-28-16](https://user-images.githubusercontent.com/44044519/66285162-fff30f80-e8fd-11e9-99ae-eda0a91608a9.png)

**Comment by Karonzhjr** [comment]
255 | 255 | 255

**Comment by miaomiaosoft** [comment]
[Keyda.zip](https://github.com/miaomiaosoft/Keyda/files/3695567/Keyda.zip)
试试
只是尝试解决出错
识别不了这部分的特殊按键也就没法就此发声了

**Comment by Karonzhjr** [comment]
> [Keyda.zip](https://github.com/miaomiaosoft/Keyda/files/3695567/Keyda.zip)
> 试试
> 只是尝试解决出错
> 识别不了这部分的特殊按键也就没法就此发声了

这个版本已解决该问题，谢谢

**Comment by bala289** [comment]
用的最新版本，我也有这个错，数组成员超出下表定义
> 识别不了这部分的特殊按键也就没法就此发声了
是fn 键和 f1，f2调节亮度两个键，发不了声没事因为不常用，就是按了会报错就尴尬了。

**Comment by miaomiaosoft** [comment]
> 用的最新版本，我也有这个错，数组成员超出下表定义
> 
> > 识别不了这部分的特殊按键也就没法就此发声了
> > 是fn 键和 f1，f2调节亮度两个键，发不了声没事因为不常用，就是按了会报错就尴尬了。

那你下载上面那个TEST程序同样的操作一遍反馈给我

**Comment by bala289** [comment]
> [Keyda.zip](https://github.com/miaomiaosoft/Keyda/files/3695567/Keyda.zip)
> 试试
> 只是尝试解决出错
> 识别不了这部分的特殊按键也就没法就此发声了

用了你给的这个包里的，不报错并且也能识别发声。

然后我是用那个test测了一下，
我的是这样的：
FN ：255
F1 :   112
F2 ：113

**Comment by miaomiaosoft** [comment]
行，那就先这么用着吧
