### ISSUE TITLE
笔记本键盘有些按键没有声音;Windows的任务计划程序也没有声音

### ISSUE THREAD

**Issue by zyp997** [miaomiaosoft/Keyda#18]
笔记本键盘最上面一排的功能键有些是没有声音的。
以及在Windows的任务计划程序中打字也没有声音。

**Comment by miaomiaosoft** [comment]
具体哪些功能键，跟他类似的吗？https://github.com/miaomiaosoft/Keyda/issues/17
如果是F1-F12之类的功能键是有声音的
虽然已知有一些进程会影响按键声音但我这测试任务计划下是有声音的，检查你的配置是不是开了进程禁用功能并把MMC.EXE添加到了进程禁用名单

**Comment by zyp997** [comment]
是F1-F12之类的功能键。貌似是我笔记本的问题，有些功能键按下去对笔记本没有任何操作，可能就是这个原因。
我电脑上装了VMware虚拟机，我已经把进程禁用方式设为0了，还是没有声音。

**Comment by miaomiaosoft** [comment]
那说不定可能键盘有问题
我临时写了个测试程序，运行后依次按下一次不发声的F1-F12按键，然后把测试程序里的文本复制给我，你可用来测试是不是真的是键盘问题，我也可以着判断大概是哪的问题
[TEST.zip](https://github.com/miaomiaosoft/Keyda/files/3694664/TEST.zip)

**Comment by zyp997** [comment]
我按下无法发声的功能键，没有任何文本出来。

**Comment by miaomiaosoft** [comment]
那估计就是那几个键位失灵了
至于任务计划程序下没声音我暂时还不知道是哪的问题，能解决的话我会再回复你

**Comment by zyp997** [comment]
@miaomiaosoft 
还有就是在几个软件中，比如SSTAP以及Netch中，也是没有声音的。
SSTAP：https://github.com/FQrabbit/SSTap-Rule/releases/tag/SSTap常用版本及去广告
Netch：https://github.com/NetchX/Netch/releases

在按Alt+Tab键时的按Tab键连续切换程序，后续的Tab也是没有声音的。

**Comment by miaomiaosoft** [comment]
真巧，这俩程序我刚好有装，不过也是正常的，你确定是管理员权限运行的KEYDA么
Alt+Tab键后续没声音是因为其中有个按键没有松开，其实还属于按下状态所以不重新发声，这属于已知的小BUG吧，因为这块的逻辑不太好处理故放弃修复

**Comment by zyp997** [comment]
管理员权限运行，解决了任务计划程序和软件无法发声的问题。（搞了半天原来是这个问题.....😂）
因为我设置成自启动了，所以不会手动去以管理员身份运行。希望能在readme中加入这项说明。

**Comment by miaomiaosoft** [comment]
OK，已加上说明
