### ISSUE TITLE
希望添加一个功能：右键能够重启程序

### ISSUE THREAD

**Issue by zyp997** [miaomiaosoft/Keyda#19]
RT。
因为切换声卡通道时，一般都需要手动重启程序才能生效。就想能不能右键图标时，添加个选项能够让它自动重启程序。

**Comment by miaomiaosoft** [comment]
不是有个 “重载配置” 功能
或者试试这个，改完会自动重载：
[Keyda.zip](https://github.com/miaomiaosoft/Keyda/files/3706444/Keyda.zip)

**Comment by miaomiaosoft** [comment]
使用上面这个程序前不嫌麻烦的话先帮我测试下
手工编辑下配置文件，将声卡选择那改成-1：
声卡选择=-1

看看当你使用不同意源时程序会不会自动切换

**Comment by zyp997** [comment]
我用你新给我的压缩包，已经设置成了-1。
我连蓝牙时不会自动切换，不过我换声卡通道时，就能切回来，不需要重启程序了。

**Comment by miaomiaosoft** [comment]
OK
