### ISSUE TITLE
Keyda 隐藏托盘图标

### ISSUE THREAD

**Issue by Karonzhjr** [miaomiaosoft/Keyda#2]
能否增加“隐藏托盘图标”功能呢？

**Comment by miaomiaosoft** [comment]
可以，下个版本更新

**Comment by miaomiaosoft** [comment]
[Keyda.zip](https://github.com/miaomiaosoft/Keyda/files/3028054/Keyda.zip)

先用着吧，用前删除旧的CONFIG配置文件
运行一次，手工修改CONFIG，隐藏托盘=1 就是不显示托盘
重启程序生效

**Comment by Karonzhjr** [comment]
在CONFIG.ini中添加：隐藏托盘=1
托盘还是显示图标

操作步骤：删除旧的CONFIG配置文件，运行一次，手工修改CONFIG，隐藏托盘=1

**Comment by miaomiaosoft** [comment]
是用上面发的这个么，我这测试没问题啊
修改完要重启软件生效

**Comment by Karonzhjr** [comment]
是的，用的3.1版

**Comment by miaomiaosoft** [comment]
![QQ截图20190401154412](https://user-images.githubusercontent.com/4084875/55311262-01e29e80-5495-11e9-8d15-eea65a1be115.jpg)
可我上传的是3.2的啊。。。你检查下文件

**Comment by Karonzhjr** [comment]
啊，又更新了，好的，我马上下载试下

**Comment by Karonzhjr** [comment]
3.2版本：在CONFIG.ini中添加：隐藏托盘=1，托盘还是显示图标

**Comment by miaomiaosoft** [comment]
不是添加，里面有这一项  你改成1就是了

**Comment by miaomiaosoft** [comment]
没有这一项那就是你操作问题

**Comment by Karonzhjr** [comment]
已搞定，谢谢
