### ISSUE TITLE
软件运行中我没有没有操作电脑，但报错了，错误代码：4

### ISSUE THREAD

**Issue by Karonzhjr** [miaomiaosoft/Keyda#22]
![Lily_Screenshot_2019年10月16日06时47分01秒](https://user-images.githubusercontent.com/44044519/68176101-75660480-ffbe-11e9-9c13-cfe1e5c00bbf.png)

Keyda 3.8
报错前我没有操作电脑
win 10 1909 64位

**Comment by Karonzhjr** [comment]
报错好几次了

**Comment by miaomiaosoft** [comment]
这就难办了，没操作自己还会出错我很难定位出错的地方

依次试以下几个配置，或者同时配置
调试功能=1
离线版本=1
屏幕按键=0
进程禁用=0

**Comment by Karonzhjr** [comment]
是的，用的挺好的，我试下。
