### ISSUE TITLE
QQ登录界面输入密码时，一直有按键音效

### ISSUE THREAD

**Issue by Karonzhjr** [miaomiaosoft/Keyda#23]
在QQ登录界面
![QQ截图20191130223519](https://user-images.githubusercontent.com/44044519/69901843-d87e6780-13c1-11ea-86ba-07770981aab1.png)
输入密码时，每输入一位，按键音效都一直自动有，持续好几秒钟才停止，但是这期间我并没有按键盘的任何键。

**Comment by miaomiaosoft** [comment]
QQ有防键盘记录的保护措施，好像就是模拟输入假的字符来阻止真实密码被可能的键盘钩子记录，这个解决不了
你可以在配置里把QQ的进程添加到排除进程名单那里

**Comment by Karonzhjr** [comment]
ok，已禁用，谢谢你
