### ISSUE TITLE
windows在切换播放设备后，keyda还是使用旧的设备播放

### ISSUE THREAD

**Issue by editcue** [miaomiaosoft/Keyda#25]
windows在切换播放设备后，没有keyda还是使用旧的设备播放。
希望能跟随系统默认播放设备播放。又或者可以在界面让用户选择通过什么设备播放声音。

**Comment by miaomiaosoft** [comment]
试试修改配置文件里的“声卡选择”
-1是默认
如果是其他声卡需要自己一个个尝试修改，从0开始
1
2
3
...

程序左上角图标点右键也有更改声卡的功能

**Comment by editcue** [comment]
我更改windows播放设备设置后，keyda没有使用新设置的设备播放音效。是因为程序没有监听windows修改“默认播放设备”的事件并刷新设置吗？

**Comment by miaomiaosoft** [comment]
通常播放设备不会经常更改，所以没有自动刷新之类的功能
