### ISSUE TITLE
功能增加建议

### ISSUE THREAD

**Issue by neko-caoxi** [miaomiaosoft/Keyda#27]
希望作者大大，提供一个可以隐藏按键上屏的选项开关，有时候并不希望按键在屏幕上显示，这个软件要比Tickeys功能更丰富，也更容易上手，小彩蛋FBI警告也足够有趣😄

**Comment by miaomiaosoft** [comment]
取消勾选 屏幕按键就是啊

**Comment by neko-caoxi** [comment]
啊这----，眼瞎没看到，不好意思作者，感谢作者做出这么好用的软件!❤️
