### ISSUE TITLE
点击鼠标也发声

### ISSUE THREAD

**Issue by fangjinggang** [miaomiaosoft/Keyda#3]
有时候用着用着，点鼠标也会有声音，miaomiao能修复一下吗

**Comment by miaomiaosoft** [comment]
新版3.1似乎已经修复了这个问题，你该更新了

**Comment by fangjinggang** [comment]
新版挺好用的  miaomiao棒棒的  就是内存占用比老版要大了  不过也不影响使用

**Comment by fangjinggang** [comment]
> 新版3.1似乎已经修复了这个问题，你该更新了

新版的不要点  真的吓到我了  幸好我带了耳机

**Comment by miaomiaosoft** [comment]
恭喜解锁成就：不听劝告
那里点右键其实是个不常用功能菜单
