### ISSUE TITLE
win11设置开机自启无效；小键盘发声为机器人语音

### ISSUE THREAD

**Issue by K0ngYu** [miaomiaosoft/Keyda#30]
系统win11 x64
开机自启功能无效
大多数音效（如钢琴）按小键盘数字区的时候声音并不是钢琴的音效而是机器人女声读出来的，我试过3.6-3.9版本，要么是小键盘直接没声音，要么就是机器人声

**Comment by miaomiaosoft** [comment]
自启功能需要以管理员权限运行后重新设置
数字音效是一项新加的功能，可以在配置文件中关闭

**Comment by K0ngYu** [comment]
感谢，自启的问题解决了，但是数字音效相关设置确实没找到，试了一下“键盘钩子”改为1，还是同样有人声，不知道应该改哪里

**Comment by miaomiaosoft** [comment]
兄弟，是配置文件啊，不是设置里，有些小功能只在config配置文件提供。
如果实在找不到，请重新下载最新版本，放到新目录运行会自动生成！
