### ISSUE TITLE
文字乱码

### ISSUE THREAD

**Issue by yi-zelin** [miaomiaosoft/Keyda#33]

**Comment by miaomiaosoft** [comment]
https://support.qq.com/products/322047/faqs/95832

**Comment by bd-dxg** [comment]
使用了相关软件 并没有成功解决问题

![2024-09-20_13-08-28](https://github.com/user-attachments/assets/2dd2b236-b5b7-4147-a6e8-1f6062718008)

乱码问题依旧存在, 但是我必须使用 Unicode UTF-8 提供全球语言支持 功能  希望作者能修复一下这个问题

软件是3.9版本  但是托盘提示里 仍然显示3.8版本

**Comment by miaomiaosoft** [comment]
> 使用了相关软件 并没有成功解决问题
> 
> ![2024-09-20_13-08-28](https://private-user-images.githubusercontent.com/34816426/369266507-2dd2b236-b5b7-4147-a6e8-1f6062718008.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTE3NDYsIm5iZiI6MTcyNjgxMTQ0NiwicGF0aCI6Ii8zNDgxNjQyNi8zNjkyNjY1MDctMmRkMmIyMzYtYjViNy00MTQ3LWE2ZTgtMWY2MDYyNzE4MDA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA1NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYmFiODhiNzA1MGMzOGY0MWY1NjI1YjAzNWI5MGU2YmQxOTRlN2NjY2ZlOWU3OWU0NGE0Yjc3ODdlOWZmNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1wb49MbJlRMnL0YZum-krA_Fikz7JiZ3Li1MfBlhD7Y)
> 
> 乱码问题依旧存在, 但是我必须使用 Unicode UTF-8 提供全球语言支持 功能 希望作者能修复一下这个问题
> 
> 软件是3.9版本 但是托盘提示里 仍然显示3.8版本

如果你是WIN11系统并确认自己操作没问题，那么可能要使用最新版的 Locale Emulator 看看它有没有修复或兼容 ，我网盘提供的不是最新版。
如果最新版也无法解决那我也没啥好办法了。
不过这个软件只要一次配置好就可以了，不用经常打开设置窗口。

**Comment by bd-dxg** [comment]
> > 使用了相关软件 并没有成功解决问题
> > ![2024-09-20_13-08-28](https://private-user-images.githubusercontent.com/34816426/369266507-2dd2b236-b5b7-4147-a6e8-1f6062718008.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTE3NDYsIm5iZiI6MTcyNjgxMTQ0NiwicGF0aCI6Ii8zNDgxNjQyNi8zNjkyNjY1MDctMmRkMmIyMzYtYjViNy00MTQ3LWE2ZTgtMWY2MDYyNzE4MDA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA1NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYmFiODhiNzA1MGMzOGY0MWY1NjI1YjAzNWI5MGU2YmQxOTRlN2NjY2ZlOWU3OWU0NGE0Yjc3ODdlOWZmNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1wb49MbJlRMnL0YZum-krA_Fikz7JiZ3Li1MfBlhD7Y)
> > 乱码问题依旧存在, 但是我必须使用 Unicode UTF-8 提供全球语言支持 功能 希望作者能修复一下这个问题
> > 软件是3.9版本 但是托盘提示里 仍然显示3.8版本
> 
> 如果你是WIN11系统并确认自己操作没问题，那么可能要使用最新版的 Locale Emulator 看看它有没有修复或兼容 ，我网盘提供的不是最新版。 如果最新版也无法解决那我也没啥好办法了。 不过这个软件只要一次配置好就可以了，不用经常打开设置窗口。

感谢你的迅速响应, 我已经换tickeys了  这个版本即使在 Unicode UTF-8 提供全球语言支持 下 也可以正常显示不乱码 功能正常使用

![2024-09-20_13-59-17](https://github.com/user-attachments/assets/06c6d990-e5a3-42c4-8ce5-1de070c290d2)
