### ISSUE TITLE
无法下载 - 检测到病毒

### ISSUE THREAD

**Issue by Tiny1233** [miaomiaosoft/Keyda#36]
#### 我打算下载3.9版本，由于性能原因，我只能下载3.8，下载即将结束的时候，这Edge浏览器突然弹出‘无法下载 - 检测到病毒’，下载失败。我重试了两次都是这样。如图所示：
![image](https://github.com/user-attachments/assets/ac313f93-88ce-4936-98e2-2a40d476665d)

**Comment by miaomiaosoft** [comment]
一直存在误报，没啥办法，而微软自带杀毒的误报又奇高且基本没法申诉，不像360还有申诉加白通道。
我只能保证没有病毒，需要自行鉴定是否加白。
