### ISSUE TITLE
Keyda 3.5

### ISSUE THREAD

**Issue by Karonzhjr** [miaomiaosoft/Keyda#6]
您好：发现在 windows 10 1903 系统下，设置了 keyda 3.5 开机自启，但是失败哦，开机后得手动启动 keyda 3.5。

**Comment by miaomiaosoft** [comment]
检查了代码，应该没问题，开机启动是修改注册表实现，应该要管理员权限运行才会生效
如果还是不行的话，可以把KEYDA的快捷方式复制到系统的启动文件夹
例win7：C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by Karonzhjr** [comment]
好的，谢谢
