### ISSUE TITLE
中键也有声音

### ISSUE THREAD

**Issue by wenkeming** [miaomiaosoft/Keyda#8]
鼠标没试过，触摸板三指时（鼠标中键功能）会连串出现声音，屏幕按键提示的为`Win+Ctrl+Shift+`
见截图：
![issue](https://user-images.githubusercontent.com/8252267/57508455-22bfce80-7334-11e9-9095-ea697550d985.gif)

**Comment by miaomiaosoft** [comment]
https://github.com/miaomiaosoft/Keyda/files/3157143/Keyda.zip

试试这个，并确保配置中的 键盘钩子=2

**Comment by wenkeming** [comment]
还是不行，已确定键盘钩子=2，
后来试了下改成1可以，中键没有声音了

**Comment by wenkeming** [comment]
还是不行，已确定键盘钩子=2，
后来试了下改成1可以，中键没有声音了。。。

**Comment by wenkeming** [comment]
额，还是不行。改为1后其他按键也没声音了……

**Comment by miaomiaosoft** [comment]
由于我没触摸板，所以这问题我暂时也不知道如何解决

**Comment by wenkeming** [comment]
嗯，我试了，鼠标的中键没有问题，触摸板三指才会出现
