### ISSUE TITLE
建议：对于密码字段的输入，屏幕按键提示能自动隐藏

### ISSUE THREAD

**Issue by wenkeming** [miaomiaosoft/Keyda#9]
如题

**Comment by miaomiaosoft** [comment]
想法很好，但目前还没好的办法获知啥时候按的才是密码，你的情况暂时就只能在输入密码的时候暂时关掉了

**Comment by miaomiaosoft** [comment]
其实可以用已有的黑名单功能间接实现，比如不想在QQ上输入密码时显示按键可以编辑配置文件：
进程禁用=1
进程禁用方式=1
进程名单=QQ.EXE

**Comment by wenkeming** [comment]
其实QQ还好，主要是浏览器。不知道能不能像autohotkey那样，获取到应用窗口的一些属性，比如：窗口标题，类名，程序名等，这样应该就更容易判断出是不是输入密码框了

**Comment by miaomiaosoft** [comment]
浏览器都是自绘的，取窗口这类的信息不好取，取窗口下的网页内容是不是密码框就更难了，这个暂时先搁置吧
